### ISSUE TITLE
OneView version requires credentials

### ISSUE THREAD

**Issue by gzecchi** [HewlettPackard/python-hpOneView#401]
### Scenario/Intent
I'm trying to get OneView Appliance Version as indicated in [this blog post](https://developer.hpe.com/blog/hpe-oneview-api-version).
As per [documentation](http://h17007.www1.hpe.com/docs/enterprise/servers/oneview4.1/cic-api/en/index.html#rest/version) OneView version should be accessible without a login sessions (or login credential), however this SDK requires credentials dict in order to init OneViewClient instance.

### Environment Details
 - OneView SDK Version: 4.8.0 (Unreleased - Master)
 - OneView Appliance Version: 4.10.04-0370820
 - OneView Client API Version: 800
 - Python Version: 2.7.15
 - Platform: MacOS Mojave 10.14.0

### Steps to Reproduce
Execute version.py inside examples folder.

### Expected Result
{u'currentVersion': 800, u'minimumVersion': 120}

### Actual Result
Traceback (most recent call last):
  File "test_versions.py", line 35, in <module>
    oneview_client = OneViewClient(config)
  File "/Code/GitHub/python-hpOneView/hpOneView/oneview_client.py", line 128, in __init__
    self.__connection.login(config["credentials"])
KeyError: u'credentials'

**Comment by sijeesh** [comment]
@gzecchi , Sorry for the late replay and Thank you for pointing out this.
We will take this as an enhancement and work on it
