### ISSUE TITLE
Can't make a connection behind a proxy

### ISSUE THREAD

**Issue by djoreilly** [HewlettPackard/python-hpOneView#7]
this line self._validateVersion() does a GET to the server 
https://github.com/HewlettPackard/python-hpOneView/blob/master/hpOneView/connection.py#L77

but that won't work if you are behind a proxy because the proxy attributes have not been set yet.

>>> con = hpov.connection('15.126.200.41')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oreillyd/swiss/automation/venv/lib/python3.4/site-packages/hpOneView/connection.py", line 77, in __init__
    self._validateVersion()
  File "/home/oreillyd/swiss/automation/venv/lib/python3.4/site-packages/hpOneView/connection.py", line 80, in _validateVersion
    version = self.get(uri['version'])
  File "/home/oreillyd/swiss/automation/venv/lib/python3.4/site-packages/hpOneView/connection.py", line 242, in get
    resp, body = self.do_http('GET', uri, '')
  File "/home/oreillyd/swiss/automation/venv/lib/python3.4/site-packages/hpOneView/connection.py", line 142, in do_http
    conn.request(method, path, body, self._headers)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1223, in connect
    super().connect()
  File "/usr/lib/python3.4/http/client.py", line 834, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 512, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 503, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

**Comment by troyhebe** [comment]
I just pushed a patch that move the version verification out of the connection object instantiation and into the login method. This should allow the proxy to be setup correctly. Please let me know if this does not resolve the issue.

**Comment by djoreilly** [comment]
that fixed it - thanks!
